version: '3'
services:
  dvwa:
    image: vulnerables/web-dvwa
    ports:
      - "8081:80"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: root
      MYSQL_PASSWORD: rootpassword  # Adicionando a senha do MySQL
      MYSQL_HOST: dvwa-db
      MYSQL_DATABASE: dvwadb
    depends_on:
      - dvwa-db

  dvwa-db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: dvwadb

  juice-shop:
    image: bkimminich/juice-shop
    ports:
      - "8082:3000"

  mutillidae:
    image: citizenstig/nowasp
    ports:
      - "8083:80"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: root
      MYSQL_PASSWORD: rootpassword  # Adicionando a senha do MySQL
      MYSQL_HOST: mutillidae-db
      MYSQL_DATABASE: mutillidae
    depends_on:
      - mutillidae-db

  mutillidae-db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mutillidae

  webgoat:
    image: webgoat/webgoat-8.0
    ports:
      - "8084:8080"
    environment:
      TZ: "America/New_York"

  bwapp:
    image: raesene/bwapp
    ports:
      - "8085:80"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: root
      MYSQL_PASSWORD: rootpassword
      MYSQL_HOST: bwapp-db
      MYSQL_DATABASE: bwapp
    depends_on:
      - bwapp-db

  bwapp-db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: bwapp

  hackazon:
    image: ivotron/hackazon
    ports:
      - "8086:80"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: root
      MYSQL_PASSWORD: rootpassword
      MYSQL_HOST: hackazon-db
      MYSQL_DATABASE: hackazon
    depends_on:
      - hackazon-db

  hackazon-db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: hackazon

  xvwa:
    image: farrukhshah/xvwa
    ports:
      - "8087:80"
