version: '3'
services:
  flask-app:
    build: .
    ports:
      - "80:5000"
  dvwa:
    image: vulnerables/web-dvwa
    ports:
      - "0.0.0.0:8081:80"

  juice-shop:
    image: bkimminich/juice-shop
    ports:
      - "0.0.0.0:8082:3000"

  mutillidae:
    image: citizenstig/nowasp
    ports:
      - "0.0.0.0:8083:80"

  webgoat:
      image: webgoat/webgoat-8.0
      ports:
        - "0.0.0.0:8084:8080"
      environment:
        TZ: "America/New_York"


  bwapp:
    image: raesene/bwapp
    ports:
      - "0.0.0.0:8085:80"

  bwapp-db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: bwapp

  hackazon:
    image: icompman/hackazon
    ports:
      - "0.0.0.0:8086:80"
   

  hackazon-db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: hackazon

  xvwa:
    image: bitnetsecdave/xvwa
    ports:
      - "0.0.0.0:8087:80"
