version: '3'
services:
  dvwa:
    image: vulnerables/web-dvwa
    ports:
      - "8081:80"

  juice-shop:
    image: bkimminich/juice-shop
    ports:
      - "8082:3000"

  mutillidae:
    image: citizenstig/nowasp
    ports:
      - "8083:80"

  webgoat:
      image: webgoat/webgoat-8.0
      ports:
        - "8084:8080"
      environment:
        TZ: "America/New_York"


  bwapp:
    image: raesene/bwapp
    ports:
      - "8085:80"

  bwapp-db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: bwapp

  hackazon:
    image: pierrickv/hackazon
    ports:
      - "8086:80"
   

  hackazon-db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: hackazon

  xvwa:
    image: bitnetsecdave/xvwa
    ports:
      - "8087:80"
